### ISSUE TITLE
I can rename "~_~_gdindex" to another name? Like "gfiles".

### ISSUE THREAD

**Issue by FloridaStream** [maple3142/GDIndex#10]
I would like to customize some things, before changing, I would like to know what files I need to change for this change to work correctly.

I ask because there may be some detail that I don't know or just find by looking for "~ _ ~ _gdindex".

Thanks for the attention guys. 🍪 ☕️ @maple3142

**Comment by maple3142** [comment]
Yes, you can replace all the occurrence of `~_~_gdindex` in worker script and `App.vue` inside  `web`. Then you  have to rebuild `web` and modify the script src in workers script's HTML part.
