### ISSUE TITLE
部署后1101错误

### ISSUE THREAD

**Issue by liuyunfz** [maple3142/GDIndex#103]
我按照提示部署了之后，访问时cf提示1101错误，我进入后台查看错误信息，如下：
worker.js:2 Uncaught ReferenceError: handleRequest is not defined
    at worker.js:2
(anonymous) @ worker.js:2
Uncaught (in response) ReferenceError: handleRequest is not defined

**Comment by maple3142** [comment]
沒複製好

**Comment by liuyunfz** [comment]
是我的问题，两分钟后我再去看了一下发现第二行代码是我未删除的cf自带的代码。因为goindex我没删除仍然成功了所以这次也没删除。
