### ISSUE TITLE
[Feature Request] - Access to specific root Drive

### ISSUE THREAD

**Issue by alx-xlx** [maple3142/GDIndex#105]
the goindex by donwa had this feature in the script to list only a particular drive instead of all the drives in the google account, please make that as an option here too

**Comment by maple3142** [comment]
Modify the code yourself

**Comment by alx-xlx** [comment]
there is no option to configure that, I have no technical know-how to do this

**Comment by maple3142** [comment]
The simplest way is to create another account, and only share necessary team drive access to it. Or just learn to code

**Comment by alx-xlx** [comment]
ok this was pretty easy

I just had to remove one letter **"s**" and I just completed my own feature request.

![nH6CbNOwsB](https://user-images.githubusercontent.com/42188371/81774090-6cbf2f80-9507-11ea-9a28-97b0abacdebd.png)

instead of listing **drives** I had to list **drive**

**Comment by alx-xlx** [comment]
this was easy

I just had to remove the letter "**s**" and I just completed my own feature request

![nH6CbNOwsB](https://user-images.githubusercontent.com/42188371/81774521-5e254800-9508-11ea-9e6c-950b45424497.png)

instead of getting **drives** I had to list **drive**
