### ISSUE TITLE
请问如何在本地调试

### ISSUE THREAD

**Issue by chenshuangwu** [maple3142/GDIndex#110]
在本地不知如何部署调试，只能放到线上，效率太低，搜了一下没找到解决方案，求指导如何在本地部署调试。

Browser version / 瀏覽器版本:Chrome
OS version / 作業系統版本:Windows 10 64位

**Comment by maple3142** [comment]
沒有方法，我都在上面測試的

**Comment by chenshuangwu** [comment]
前端vue也是在上面测试？

**Comment by maple3142** [comment]
自己改html中的props

**Comment by chenshuangwu** [comment]
好的，谢谢！！
