### ISSUE TITLE
能不能添加多目录绑定功能

### ISSUE THREAD

**Issue by hustarbor** [maple3142/GDIndex#117]
我想在一个域名里面绑定多个root，然后可以切换

**Comment by maple3142** [comment]
不是本來就能切換了

**Comment by hustarbor** [comment]
诶，好像是有说过，有没有什么教程吗

**Comment by maple3142** [comment]
這個不是本來就有的功能嗎

**Comment by hustarbor** [comment]
> 
> 
> 這個不是本來就有的功能嗎

刚刚看到了，不好意思啊。把default_root_id设置为‘root’就可以切换多个云盘了。
大佬可不可以考虑一下多个文件夹id，以列表或者字典的形式添加

**Comment by maple3142** [comment]
不要
