### ISSUE TITLE
關於圖片查看

### ISSUE THREAD

**Issue by chincccc** [maple3142/GDIndex#119]
打開圖片查看時下方的上一張/下一張按鈕無效(此文件夾包含不止一張圖片)

瀏覽器版本: Microsoft edge Chromium 版 81.0.416.68

**Comment by maple3142** [comment]
chrome 能嗎

**Comment by chincccc** [comment]
> chrome 能嗎

試了一下也是一樣

**Comment by maple3142** [comment]
那個是正常的
