### ISSUE TITLE
[Feature Request] Add Support For Paid Link Shortner Services Like Adfly and Banners

### ISSUE THREAD

**Issue by askfriends** [maple3142/GDIndex#129]
hi;
Can you add support for paid link shortner services like adfly?
i tried to add javascript code from adfly but it didnt worked.

Also it would be nice if you add support for adding advertisement Banners from adsense or any other thirtd party services like bidvertiser, propellarads etc in multiple spaces like Top of page, in middle posts, below every post etc..

**Comment by maple3142** [comment]
Do it yoourself
