### ISSUE TITLE
播放mkv问题请教一下

### ISSUE THREAD

**Issue by bbvv77** [maple3142/GDIndex#130]
< video width="320" height="240" controls >
  < source src="720p.web.x264-xlf.mkv" type="video/webm" >
< /video >
这样mkv在chrome能播放了字幕加载没成功，我想让GDIndex也支持播放mkv。请教一下把代码加到哪里能实现？

**Comment by maple3142** [comment]
關於mkv的問題請先搜尋過，已經被問過很多遍了
要自己加的話需要學一定程度的 vue 才有辦法加
