### ISSUE TITLE
下载文件时，chrome 提示“失败 - 未发现文件”

### ISSUE THREAD

**Issue by April-BOY** [maple3142/GDIndex#132]
# Bug Description / 問題描述
下载文件时，chrome 提示“失败 - 未发现文件”

（1）使用浏览器下载已经转存到我网盘的文件时，直接报错“失败 - 未发现文件”，文件已经转存到我的网盘，下载网盘里的其他文件是没问题的，怀疑是这个文件的文件名包含“[]、/、「”和日语等字符
（2）复制下载链接到IDM中下载，报错是“404 not found”
希望作者能排查下

## Bug 示意图：
![image](https://user-images.githubusercontent.com/19245482/87743567-cef42380-c81b-11ea-80a0-3215ab50aecd.png)

![image](https://user-images.githubusercontent.com/19245482/87743518-b552dc00-c81b-11ea-8faa-ce88b90c57ef.png)

# Environment / 環境
直接使用个人使用的笔记本的浏览器上操作的

* Browser version / 瀏覽器版本:Google chrome 84
* OS version / 作業系統版本:Windows10 Pro 1909

**Comment by maple3142** [comment]
我需要有範例連結

**Comment by April-BOY** [comment]
以下是该文件的下载链接：
用户名：hanz 密码：hanz#1994

https://wandering-sound-cdfe.hanz.workers.dev/%25E5%25BD%25B1%25E8%25A7%2586/%25E7%25BA%25AA%25E5%25BD%2595%25E7%2589%2587/%5B%E6%98%9F%E7%A9%BA%E5%AD%97%E5%B9%95%E7%BB%84%5D%5B%E4%BA%8B%E4%BB%B6%E4%B9%8B%E6%B3%AA%E3%80%8C%E4%BD%A0%E5%B7%B2%E4%B8%8D%E5%9C%A8%E9%82%A3%E9%87%8C~%E4%BA%AC%E9%83%BD%E5%8A%A8%E7%94%BB%E7%BA%B5%E7%81%AB%E6%A1%88~%E3%80%8D/%2520%E4%BA%8B%E4%BB%B6%E3%81%AE%E6%B6%99%E3%80%8C%E3%81%9D%E3%81%93%E3%81%AB%2520%E3%81%82%E3%81%AA%E3%81%9F%E3%81%8C%E3%81%84%E3%81%AA%E3%81%84%EF%BD%9E%E4%BA%AC%E9%83%BD%E3%82%A2%E3%83%8B%E3%83%A1%E3%83%BC%E3%82%B7%E3%83%A7%E3%83%B3%E6%94%BE%E7%81%AB%E4%BA%8B%E4%BB%B6%E3%80%8D%5D%5B%E7%AE%80%E6%97%A5%E5%8F%8C%E8%AF%AD%5D%5B1080P%5D%5BTVrip%5D%5BMP4%5D.mp4

**Comment by maple3142** [comment]
這個的問題在於你的檔案名稱中有 `/` 符號，請自己把它的名稱改掉
