### ISSUE TITLE
Is there any way to create a text file with all links in the open directory?

### ISSUE THREAD

**Issue by bnichs5** [maple3142/GDIndex#133]
Is there anyway to auto create a txt file on the open directory that would contain every url on the open directory?

For instance:

https://test.test.workers.dev/test.txt

would contain:

https://test.test.workers.dev/friend.avi
https://test.test.workers.dev/filestream.exe
https://test.test.workers.dev/youtube/hello.mp4
https://test.test.workers.dev/youtube/HDvid.mp4
https://test.test.workers.dev/youtube/Myeyes.mp4
https://test.test.workers.dev/music/mp3/aaron_carter.mp3
https://test.test.workers.dev/music/mp3/backstreetboys.mp3

**Comment by maple3142** [comment]
You can program against Google Drive api yourself.
