### ISSUE TITLE
My team drive is not showing and other shared drives are showing. How to rectify this?

### ISSUE THREAD

**Issue by biot-spec** [maple3142/GDIndex#134]
So I have created a new shared team drive on google, say named X. Also I have subscribed to numerous other shared drives, say A,B,C,D.

Now on my worker site, under Main group, it doesn't display any content. However all the other shared drives (A,B,C,D) are visible, but X is not visible.

My problem: How do I display only X and not A,B,C,D.

**Comment by maple3142** [comment]
You can aset default root id to id of X. As for hiding others, you need to modify the code yourself.

**Comment by biot-spec** [comment]
> You can aset default root id to id of X.
How do I do that in the code?

I  believe deleting `async listFolder` will get rid of the other drives. 

I'm not a coder, so can you help me out.

**Comment by maple3142** [comment]
> > You can aset default root id to id of X.
> 
> How do I do that in the code?

Edit the config at the top.

> I believe deleting `async listFolder` will get rid of the other drives.
> 
> I'm not a coder, so can you help me out.

I believed it is asked before, you need to search issue before asking.
