### ISSUE TITLE
[Feature Request] Support copy file

### ISSUE THREAD

**Issue by CodeingBoy** [maple3142/GDIndex#14]
Downloading files might encounter "Quota exceed" error, making a copy can bypass this limit.
It will be useful if there's an api allowing user copy a file.

**Comment by maple3142** [comment]
Yes, there is an api for that: https://developers.google.com/drive/api/v2/reference/files/copy

When download quota exceeded, copy the file to temporary folder and download the file and delete it immediately? But I am not sure how this would work as I have never encountered quota exceeded error.

**Comment by CodeingBoy** [comment]
> Yes, there is an api for that: https://developers.google.com/drive/api/v2/reference/files/copy
> 
> When download quota exceeded, copy the file to temporary folder and download the file and delete it immediately? But I am not sure how this would work as I have never encountered quota exceeded error.

Thank you! You idea looks great, I will consider and try implementing it once I have spare time.
