### ISSUE TITLE
Unable to view or download

### ISSUE THREAD

**Issue by denny14368** [maple3142/GDIndex#142]
sir, Unable to view or download it tells "HTTPError: Forbidden\n    at responseErrorThrower (worker.js:177:26)\n    at async onGet (worker.js:489:19)\n    at async handleRequest (worker.js:682:42)"

**Comment by maple3142** [comment]
You have to set it up correctly

**Comment by denny14368** [comment]
sir i setup using this https://gdindex-code-builder.maple3142.net/

**Comment by maple3142** [comment]
It works for other people, so it must be you did someting wrong.
