### ISSUE TITLE
No reproduce video GDIndex

### ISSUE THREAD

**Issue by shifft3340** [maple3142/GDIndex#149]
![Captura](https://user-images.githubusercontent.com/27146772/93742429-17cdad00-fbbc-11ea-8e25-6371d77f2d92.JPG)

# Bug Description / the script has been crashing for several days without allowing video playback from google drive, I changed my account and allowed to play and once maz stopped doing it

# Environment / Google Drive

* Browser version / I have tested it in most browsers that I have on hand
* OS version / windows 10, android 8.0, 10, ios 13, 12

**Comment by maple3142** [comment]
I need you gdindex url to test

**Comment by shifft3340** [comment]
https://gd.9tu5mac.workers.dev/~viewer/video?urlBase64=aHR0cHM6Ly9nZC45dHU1bWFjLndvcmtlcnMuZGV2L0lOQ1JVSVNFUy9Db21vJTIwQ2VycmFyJTIwRW4lMjBDdWFyZW50ZW5hJTIwQWxleCUyMERleSUyMElOQ1JVSVNFUy5tcDQ%3D


At this moment the video is running, but there is a moment when it throws me errors, if you like when that happens I can write immediately and you will notice

**Comment by maple3142** [comment]
I think it is possible that you download too much from google drive so that your account got rate limited. You can test it by downloading the video from official google drive web app.

**Comment by shifft3340** [comment]
If you try to play now it will not allow you to see the video, where the script is hosted according to them it allowed me 100,000 requests per day I have it mounted on cloudflare.com in the workers section

**Comment by maple3142** [comment]
The "quota" I mean is imposed by Google, not Cloudflare.

**Comment by shifft3340** [comment]
I have a shared drive in google drive, I comment that with unlimited google would

**Comment by maple3142** [comment]
The quota is not disk size. Google will limit how much bandwidth can go out per day by drive.

**Comment by shifft3340** [comment]
seriously, damn bad for google, I think I have to see another wider video alternative, if you know something that can help with google I would be happy to hear
