### ISSUE TITLE
How to google drive id?

### ISSUE THREAD

**Issue by wulandrima1** [maple3142/GDIndex#157]
how to show link original google drive id ?

**Comment by maple3142** [comment]
What?

**Comment by wulandrima1** [comment]
> What?

how to show 'link original google drive'

ex
![a](https://user-images.githubusercontent.com/71014870/95846479-a970aa80-0d75-11eb-9b3a-13754adcb0c9.jpg)

**Comment by maple3142** [comment]
It can't do that
