### ISSUE TITLE
挂载某一个团队盘的时候，可以通过左上角的团队盘下拉，进入到其他盘

### ISSUE THREAD

**Issue by meichuanyi** [maple3142/GDIndex#161]
# Bug Description / 問題描述

# Environment / 環境

* Browser version / 瀏覽器版本:mac Chrome 最新版
* OS version / 作業系統版本: Mac OS 10.15.3
挂载某一个团队盘的时候，可以通过左上角的团队盘下拉，进入到其他盘

**Comment by maple3142** [comment]
本來就是這樣的
