### ISSUE TITLE
上传较大的文件会失败

### ISSUE THREAD

**Issue by luluxiaoyu** [maple3142/GDIndex#163]
# Bug Description / 問題描述

上传较大的文件会失败，小一点的文件可以成功
# Environment / 環境

* Browser version / 瀏覽器版本:Chrome
* OS version / 作業系統版本:Windows 7

**Comment by maple3142** [comment]
![image](https://user-images.githubusercontent.com/9370547/98435871-90a7aa80-2111-11eb-9f86-2c523e1c9299.png)
