### ISSUE TITLE
I can't view shared folders.

### ISSUE THREAD

**Issue by PanPeople** [maple3142/GDIndex#165]
Bug Description / 問題描述

I can't view shared folders. I mean it visible in my list, but i not able to see the content of this shared folder

Environment / 環境

* Browser version / 瀏覽器版本: Chrome 86.0.4240.193
* OS version / 作業系統版本: Windows 10 Pro

**Comment by maple3142** [comment]
Need example

**Comment by PanPeople** [comment]
so i have this link: https://drive.google.com/drive/folders/1SDNoRhgGOhV301yF4G9oZfI7SZAYEB-D?usp=sharing
mount it here:
![image](https://user-images.githubusercontent.com/30329682/98920914-f6f54a00-24d0-11eb-8af1-22de8cf2acd2.png)
and i have got this:
![image](https://user-images.githubusercontent.com/30329682/98921035-2015da80-24d1-11eb-821c-6c3a60838942.png)

**Comment by maple3142** [comment]
GDIndex ≠ Google Drive

**Comment by PanPeople** [comment]
So i can list all my files execpt links to other files/drives?
