### ISSUE TITLE
Is it possible to have multiple default_root_id?

### ISSUE THREAD

**Issue by PanPeople** [maple3142/GDIndex#169]
Is it possible to have multiple root_id? Or is it hard to implement? It would be a nice feature if we want to acess some shared folders

**Comment by maple3142** [comment]
No, and it is not needed.
`default_root_id` only means the default drive to open when drive is not specified, so you can just select other drvie in menu (if exists).

**Comment by PanPeople** [comment]
But i don't have "Gsuite Business+ Account" i wan't to know is it possible to switch between shared folder, because even if they are visible in my root folder i can't acces them but you said that it is GDIndex is not a Google Drive. If i change the default_root_it to the prefig of my shared folder it works, but i don't wan't to do it manually every time when i want to have acces to my shared folder.

**Comment by maple3142** [comment]
It is not supported by this project. Maybe you can use create a shortcut in your drive

**Comment by PanPeople** [comment]
And what about setting the default_root_id in the url?

**Comment by maple3142** [comment]
You can pass rootId already

**Comment by PanPeople** [comment]
Sorry but how to get it work in lite mode? passing rootid in default/not lite mode works excelent but will it work i nlite mode?

**Comment by maple3142** [comment]
Lite mode doesn't support that

**Comment by PanPeople** [comment]
Any chance for adding such a feature?

**Comment by maple3142** [comment]
No
