### ISSUE TITLE
视频播放不支持 mkv 格式

### ISSUE THREAD

**Issue by yangchuansheng** [maple3142/GDIndex#17]
大佬，mkv格式不不能播放啊，有空支持一下

**Comment by maple3142** [comment]
mkv並不能算是一種格式，而是一種容器而已，裡面實際上是什麼格式無法得知，所以瀏覽器播放不了

**Comment by yangchuansheng** [comment]
goindex是可以播放的啊，gdindex不行，肯定是有办法的

maple <notifications@github.com> 于 2019年12月10日周二 下午2:02写道：

**Comment by maple3142** [comment]
也一定不是每個mkv都能播放的

**Comment by yangchuansheng** [comment]
都可以播放的，只是有的没声音，不管能不能播放，希望 gdindex 对 mkv 的默认处理行为是预览，而不是下载

maple <notifications@github.com> 于2019年12月11日周三 上午11:39写道：
