### ISSUE TITLE
New Issue Please help

### ISSUE THREAD

**Issue by coolboy007** [maple3142/GDIndex#179]
why this problem show? how to fix it? 
![Screenshot_2020-12-26-16-49-52-360_com android chrome](https://user-images.githubusercontent.com/61577388/103150492-ba3c9400-479a-11eb-8d52-b18f6905d687.png

**Comment by maple3142** [comment]
Maybe it is not properly configured.

**Comment by coolboy007** [comment]
> Maybe it is not properly configured.

but i used for 5 months. why now not working?

**Comment by maple3142** [comment]
I don't know, you need to fix it yourself

**Comment by coolboy007** [comment]
> I don't know, you need to fix it yourself

ohk... and how to fix Download limit quota exceed error??

**Comment by maple3142** [comment]
Don't download too much

**Comment by coolboy007** [comment]
> Don't download too much

but how to reset that?

**Comment by maple3142** [comment]
You can't.
You nned to wait
