### ISSUE TITLE
上传失败

### ISSUE THREAD

**Issue by jiujiu1** [maple3142/GDIndex#182]
使用快速方法部署的，大文件无法上传成功，卡住了。。如何解决？？
![阿里旺旺图片20210124195532](https://user-images.githubusercontent.com/17944972/105629511-5d59f980-5e7e-11eb-9e1a-0d45b2b3f6c3.jpg)

**Comment by jiujiu1** [comment]
试过好几次。

**Comment by maple3142** [comment]
正常的
