### ISSUE TITLE
PDF viewer error on mobile devices

### ISSUE THREAD

**Issue by skmaiti2050** [maple3142/GDIndex#29]
It shows up an error "This plugin is not supported" on a web browser on mobile device, tried with different device, same issue. Even please allow to view doc/docx, ppt/pptx too on the mobile devices as it is common document format.

User-agent:
Mozilla/5.0 (Linux; Android 10) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/77.0.3865.92 Mobile Safari/537.36

**Comment by maple3142** [comment]
Unable to view pdf is mostly safari's problem, as other browser on Android work fine.
And it is basically impossible to view doc/docx, ppt/pptx on website easily.

**Comment by skmaiti2050** [comment]
It wasn't safari, it was Chrome on Android with latest webview
