### ISSUE TITLE
当目录中文件数超过1000，无法列出完整文件列表。

### ISSUE THREAD

**Issue by kuk111111** [maple3142/GDIndex#3]
首先感谢作者的项目
但我发现目录中文件数超过1000个，依旧无法列出完整文件列表
如果是由于API限制的话，能否实现分页来解决该问题？

**Comment by SelfEnough** [comment]
同求

**Comment by maple3142** [comment]
在大概幾天內就會加入了，之前在忙期中考

**Comment by maple3142** [comment]
@kuk111111 @SelfEnough 可以更新 Workers 的腳本看看，目前最新的版本已經把它修復了
