### ISSUE TITLE
[Feature Request] download .strm file for each link

### ISSUE THREAD

**Issue by bnichs5** [maple3142/GDIndex#32]
for those using this for movies/tv shows.

is there a way to turn each link into an .strm file.
strm file is just a text file which contains the link for the file itself. 

as an example:
inside the file would only be https://gdindex-demo.maple3142.workers.dev/Sintel/Sintel.mp4 and the file name would be called Sintel.mp4.strm

if you could make it recursive that would be awesome too. This is where it does the above but keeps the folder/directory structure as well. 

similar to ddurdle's google drive python script

I hope this makes sense! Let me know if it is confusing.

**Comment by maple3142** [comment]
I don't get why the need of **strm** file? Wouldn't copying the link of a video to player just works?

**Comment by bnichs5** [comment]
for emby. so i can serve the the videos to family/friends using my emby server.

**Comment by maple3142** [comment]
I think it doesn't have to actually create a file.
If I just return a url for any url that ends with `.strm`, will those software work with this?
For example: `https://whatever.domain/foo/bar/test.file.strm` -> A text file contains `https://whatever.domain/foo/bar/test.file`

**Comment by bnichs5** [comment]
The end result- I'd like to be able to automatically download a strm file
for each Google drive file/url in the current directory and all sub
directories recursively. Your example of the strm file is accurate.

**Comment by maple3142** [comment]
Like this? https://gdindex-demo.maple3142.workers.dev/non-existence.mp4.strm

Find `onGet` function in your worker code, and add these to it like the image below:
```javascript
    if (path.endsWith('.strm')) {
      return new Response('https://gdindex-demo.maple3142.workers.dev' + path.slice(0, -5), {
        status: 200,
        headers: {
          'Content-Type': 'text/plain'
        }
      })
    }
```

![](https://i.imgur.com/pwZBPLh.png)

**Comment by bnichs5** [comment]
I'm not too familiar with the code, but I opened the file and it contains
exactly what I'm looking for.

Is there a way to allow automatic download of all the strm creations as
well?

**Comment by bnichs5** [comment]
Or do you know how to scrape the site/links.
Wget doesn't seem to work for dynamic websites.

**Comment by maple3142** [comment]
If fact, I have a plan to implement a lite version option. It will make the index looks like what nginx have.

**Comment by bnichs5** [comment]
Will adding the lite version help to download all the files at once?
Does it allow for wget to work?

**Comment by maple3142** [comment]
Yes, wget can crawl some static directory listing like this: https://stackoverflow.com/questions/273743/using-wget-to-recursively-fetch-a-directory-with-arbitrary-files-in-it

**Comment by bnichs5** [comment]
Thank you. I really appreciate you adding this feature. I hope it works.

**Comment by maple3142** [comment]
Demo: https://gdindex-demo-lite.maple3142.workers.dev/
You can follow the readme to use lite mode now!

**Comment by bnichs5** [comment]
Thank you. I can't wait to try this out. 

I know there's a lot of people trying to do similar to me so you're helping them out by doing this as well.

**Comment by bnichs5** [comment]
I tried adding the code to the onget function but it isnt producing any .strm files.

**Comment by maple3142** [comment]
What mode are you using? lite or normal?

**Comment by bnichs5** [comment]
Lite

**Comment by bnichs5** [comment]
Also what I noticed is that if a folder or title has a space in it, the link will also have the space instead of %20 I think. Is there anyway to convert the spaces to %20 ?

**Comment by bnichs5** [comment]
Following up on this. Any ideas?

**Comment by maple3142** [comment]
Wrap that `path.slice(0,-5)` with `encodeURI()` should work, but I haven't test it.

**Comment by bnichs5** [comment]
Thanks! It did work!

Have you thought of anything for my prior question though? The .strm files aren't showing up in the index. They exist, but it's almost like they are hidden. Unless you know the url to enter, then you cant find them.

**Comment by maple3142** [comment]
It that needed for emby to function correctly?

**Comment by bnichs5** [comment]
Yes. I essentially would need to download each of the .strm files locally.
That's why I was talking about downloading each of the .strms through wget
before. But they don't show up.

**Comment by maple3142** [comment]
Modify the code like this should work:
![](https://i.imgur.com/0xv6zCC.png)

Added line:
```js
const duplicateFiles = files.concat(files.filter(f => f.mimeType !== 'application/vnd.google-apps.folder').map(f => ({ ...f, name: f.name + '.strm' })))
```

**Comment by bnichs5** [comment]
It doesnt appear to be working.

**Comment by bnichs5** [comment]
Nevermind it does work. Thanks!
