### ISSUE TITLE
是否有计划支持 Google Cloud Functions

### ISSUE THREAD

**Issue by ceecx** [maple3142/GDIndex#38]
CF 速度太慢了，希望有这个分支，最近自己也在尝试。

**Comment by maple3142** [comment]
理論上 https://github.com/dollarshaveclub/cloudworker 應該有幫助

**Comment by ceecx** [comment]
如果个人使用的话，我觉得费用可以忽略，这样的确很方便。
目前 CloudFlare 回源速度太慢，打开也不理想，对于国内。

**Comment by iYato** [comment]
> 理論上 [dollarshaveclub/cloudworker](https://github.com/dollarshaveclub/cloudworker) 應該有幫助
> 我不打算支援這個的原因是因為 cloud functions 的計費有含流量在裡面

有可能支持其他 Serverless 平台吗？

**Comment by maple3142** [comment]
@iYato 有這種需求的話請自用我上面提供的那個去研究，不在此專案的範圍內

**Comment by blackjack4494** [comment]
Tho I don't understand a word. I also asked me the same if it is possible to deploy it as google cloud functions / run / apps script. It should be definitely possible. However it would take some major modification / code restructuring.

**Comment by maple3142** [comment]
This project is designed for Cloudflare Workers, so we need a service worker emulation layer to have it work on other platform. Unfortunately, https://github.com/dollarshaveclub/cloudworker isn't complete, which failed to run GDIndex.

**Comment by maple3142** [comment]
Close this as it is basically the same as #53
