### ISSUE TITLE
请问为什么mp4文件无法播放?

### ISSUE THREAD

**Issue by zglzw** [maple3142/GDIndex#40]
无论是用向导方式还是手动方式，最后播放google drive里的mp4文件只有白屏和声音，没有画面

**Comment by maple3142** [comment]
下載回來能播放嗎？

**Comment by zglzw** [comment]
可以播放，在Google drive里直接预览也有画面

**Comment by maple3142** [comment]
有範例的檔案嗎？

**Comment by zglzw** [comment]
https://shy-haze-da19.zglzw.workers.dev

google chrome 版本 79.0.3945.117（正式版本） （64 位）

**Comment by zglzw** [comment]
今天我又打开看了一下还是不行

**Comment by CuteLouise** [comment]
> 今天我又打开看了一下还是不行

你传个小于1G的mp4文件试试

**Comment by zglzw** [comment]
好的我这就去试试

**Comment by zglzw** [comment]
我试了一下小于1G的MP4文件可以播放。我Google drive里其他超过1G的MP4文件都是H265格式，不知道无法播放与这个有没有关系。

**Comment by maple3142** [comment]
@zglzw H.265 播放不了是正常的
https://caniuse.com/#feat=hevc

**Comment by zglzw** [comment]
好的，那我再试试其他的大于1G的MP4文件
