### ISSUE TITLE
Add a search option

### ISSUE THREAD

**Issue by Xexanoath** [maple3142/GDIndex#41]
This is one of my most required feature because having everything in different folders cause jumbos and misshaps...I just wish you to add this

**Comment by ParveenBhadooOfficial** [comment]
@maple3142 

I've added a search option
https://github.com/ParveenBhadooOfficial/Bhadoo-Drive-Index

Basic Code:
https://cdn.jsdelivr.net/gh/ParveenBhadooOfficial/BhadooDriveIndex/web/src/search.css
https://cdn.jsdelivr.net/npm/jquery@3.2.1/dist/jquery.min.js

<script>$(document).ready(function(){ $('#search').keyup(function(){ var text = $(this).val(); $('.v-list-item').hide(); $('.v-list-item:contains("'+text+'")').closest('.v-list-item').show(); }); }); $.expr[":"].contains = $.expr.createPseudo(function(arg) { return function( elem ) { return $(elem).text().toUpperCase().indexOf(arg.toUpperCase()) >= 0; }; });</script>

<div class="drive-index-footer"> <center> <div class='container'> <div> <input type='text' id='search' placeholder='Search After Complete Loading'></div></center></div>

The option can be tested here: https://googledri.ve.workers.dev

It is browser side search so works only after page is loaded.

**Comment by maple3142** [comment]
@ParveenBhadooOfficial Your implementation is essentially same as browser's crtl+f, which is not what @Towha want (probably).

**Comment by ParveenBhadooOfficial** [comment]
@maple3142 It's not for @Towha It's for everyone, as in mobile using ctrl+f is not possible and this method is pretty easy and many users want this. That's why i proposed. When i added this to my index, users are pretty much happy getting this Sir.

**Comment by maple3142** [comment]
@ParveenBhadooOfficial What I mean by `ctrl+f` is browser's built in searching functionality, which most mobile browsers do have. eg. Chrome, Firefox

**Comment by ParveenBhadooOfficial** [comment]
@maple3142 Try [this](https://one.driveindex.ga/) in mobile device. You'll understand why this could be helpful instead of CTRL+F.

**Comment by ParveenBhadooOfficial** [comment]
@maple3142 look at this for search function
https://github.com/yanzai/goindex
