### ISSUE TITLE
上传文件问题

### ISSUE THREAD

**Issue by x229728321** [maple3142/GDIndex#43]
本地上传文件大小是不是有限制，上传文件大概超过3-400m的文件就停止上传了，上传失败

**Comment by huoshenw** [comment]
我也是这个问题

**Comment by maple3142** [comment]
上傳大檔案有機會隨機失敗，和從網址上傳是一樣的

**Comment by huoshenw** [comment]
那么有其他的GD免翻墙上传方案吗？或者有没有办法从Onedrive转存到GD

**Comment by maple3142** [comment]
用牆外的vps用rclone可以轉存
