### ISSUE TITLE
epub的背景色修改下吧

### ISSUE THREAD

**Issue by jackjieYYY** [maple3142/GDIndex#5]
纯白色看久了真的会瞎的

而且又看不清字
![TIM图片20191023020338](https://user-images.githubusercontent.com/53422254/67300268-6fd9da80-f539-11e9-9168-b124cde3f8ce.png)

**Comment by maple3142** [comment]
這不是我能改的，閱讀器是別人寫的
要更多的設定選項可以考慮下載回來用專門的閱讀器閱讀
