### ISSUE TITLE
mkv videos cannot be streamed

### ISSUE THREAD

**Issue by aykuxt** [maple3142/GDIndex#51]
since html5 players can play mkv videos and GOindex support it too it should also work on GDindex.

**Comment by maple3142** [comment]
HTML5 players can't play all mkv, because mkv is a container format.

**Comment by aykuxt** [comment]
Actually they can be streamed when mkv source is set to video/mp4 in video tag.
GOindex support it as well.

**Comment by maple3142** [comment]
> Actually they can be streamed when mkv source is set to video/mp4 in video tag.
> GOindex support it as well.

Except for you can't know that before browser starts fetching the video to your browser.
