### ISSUE TITLE
希望在线播放视频可以支持多种格式

### ISSUE THREAD

**Issue by lyydhy** [maple3142/GDIndex#58]
例如mkv 这些

**Comment by maple3142** [comment]
能播放什麼影片是看瀏覽器支援的程度如何，不是我能決定的

**Comment by lyydhy** [comment]
浏览器是支持的 好像是你代码里面没有对mkv进行处理 （导致点击过后就是下载 并没跳转到videoview） 只对mp4 flv处理了 好像是  我不太懂 vue

**Comment by maple3142** [comment]
mkv 是一種容器格式，裡面包含的影片格式瀏覽器不一定支援
例如一個包含 mp4 的 mkv 瀏覽器肯定是支援的，但是如果是包含其他特殊格式的都不一定了
我沒加入 mkv 就是因為我試過用瀏覽器播放一個特殊的 mkv，結果播放失敗

**Comment by lyydhy** [comment]
大佬可以添加一个播放音乐的控件吗？ 而不是跳转播放
