### ISSUE TITLE
link without removing authorisation 

### ISSUE THREAD

**Issue by alenpaul2001** [maple3142/GDIndex#62]
Hey I like to know weather we can download the links without authorisation.
downloading the link in other platforms like aria2c outputs authorisation error.

**Comment by alenpaul2001** [comment]
i believe you understand what i am trying to say 
I think its possible by removing a few lines.
this repo does that job https://github.com/donwa/goindex 
But i love the way u materialized the page and added features

**Comment by maple3142** [comment]
Disable authorization entirely should do the work
Or you can configure your downloader to use you credentials, because it use HTTP basic auth, which is a widely supported standard

**Comment by TheMovieStore** [comment]
By any chance can we only use authentication only for the root directory , and not direct links . I mean direct download can start without pass.

**Comment by TheMovieStore** [comment]
> 
> 
> i believe you understand what i am trying to say
> I think its possible by removing a few lines.
> this repo does that job https://github.com/donwa/goindex
> But i love the way u materialized the page and added features

https://github.com/maple3142/GDIndex/issues/46#issuecomment-608016890 , try this :)

**Comment by TheMovieStore** [comment]
> 
> 
> Disabling authorization entirely should do the work
> Or you can configure your downloader to use you credentials, because it use HTTP basic auth, which is a widely supported standard

Thank You , Sar awesome work. :)

**Comment by alenpaul2001** [comment]
> > Disabling authorization entirely should do the work
> > Or you can configure your downloader to use you credentials, because it use HTTP basic auth, which is a widely supported standard
> 
> Thank You , Sar awesome work. :)

perfect thanks for the info
