### ISSUE TITLE
PDF无法在线观看 希望增加README的自动显示

### ISSUE THREAD

**Issue by kolicime** [maple3142/GDIndex#71]
打开PDF文件会唤起IDM下载（不确定是不是插件的问题），但是EPUB格式的文件没问题。
希望能增加类似goindex的README或者是HEAD文件自动显示的问题
而且暂时TXT和MD文件似乎会有编码问题

**Comment by maple3142** [comment]
@kolicime 把 IDM 的插件移除掉看看

Readme 我認為是很多餘的功能

編碼一律使用 utf-8

**Comment by kolicime** [comment]
关掉插件之后就可以了

txt文件编码是utf-8，但是还是乱码

**Comment by maple3142** [comment]
@kolicime 範例？

**Comment by kolicime** [comment]
我用notepad++打开显示的确实是UTF-8文件我上传了您可以用这个测试一下[下载链接](https://ws28.cn/f/26o189gloyw)，这个worker是我拿来给宿友放大姐姐的，链接就不发出来了:)。

**Comment by maple3142** [comment]
@kolicime 我需要有個 demo

**Comment by kolicime** [comment]
[文件地址](https://test.kolicime.workers.dev/README.TXT)

**Comment by fengzhao** [comment]
> 我用notepad++打开显示的确实是UTF-8文件我上传了您可以用这个测试一下[下载链接](https://ws28.cn/f/26o189gloyw)，这个worker是我拿来给宿友放大姐姐的，链接就不发出来了:)。

大姐姐在哪里？

**Comment by maple3142** [comment]
那就移除 IDM

**Comment by jidanyunmian** [comment]
把你的域名添加到idm不要自动开始下载就好了，idm插件开着也没问题
