### ISSUE TITLE
Hide root id

### ISSUE THREAD

**Issue by churongcon** [maple3142/GDIndex#72]
Hello I wanna hide root ID

ex: https://gdindex-demo.maple3142.workers.dev/?rootId=root

Only access when user have folder id https://gdindex-demo.maple3142.workers.dev/?rootId=0ANuznjfLOB9mUk9PVA

**Comment by maple3142** [comment]
Hide root id for security is pointless, but if you really want to do it, just set it as defaultRootId

**Comment by churongcon** [comment]
I just want to share specific folder? how to do it

**Comment by churongcon** [comment]
@maple3142

**Comment by maple3142** [comment]
Easy way: Create a another account and share those files to that account, and create another instance of GDIndex using the new account.
Hard way: Read the code and edit accordingly

**Comment by churongcon** [comment]
I dont have more unlimited storage to create another :(

Same goindex have password for specific folder
https://github.com/yanzai/goindex

**Comment by maple3142** [comment]
You don't have to, just create another account and share access to new account should do the trick.
