### ISSUE TITLE
File scanning issue

### ISSUE THREAD

**Issue by rootxad** [maple3142/GDIndex#73]
I dont know if this is a issue or not but files detected as virus are not downloadable ?

我不知道这是否是一个问题，但是检测为病毒的文件无法下载？(Simplified)

我不知道這是否是一個問題，但是檢測為病毒的文件無法下載？(Traditional)

**Comment by maple3142** [comment]
@rootxad Do you have example?

**Comment by rootxad** [comment]
Yea

Here: [Link](https://root2.officialmohammadusman.workers.dev/UniProjects/IDMBeta2.zip?rootId=0ABxEChENyKGpUk9PVA)

**Comment by rootxad** [comment]
and when i switch it to lite version and download get this error:

```
{
 "error": {
  "errors": [
   {
    "domain": "global",
    "reason": "cannotDownloadAbusiveFile",
    "message": "This file has been identified as malware or spam and cannot be downloaded."
   }
  ],
  "code": 403,
  "message": "This file has been identified as malware or spam and cannot be downloaded."
 }
}
```

**Comment by rootxad** [comment]
Not happening in Team Drives but in personal 15 gb ones too.

**Comment by rootxad** [comment]
@maple3142 ??

**Comment by maple3142** [comment]
Try deploy it again using updated code
