### ISSUE TITLE
As i update to the malicious code other files fails to download

### ISSUE THREAD

**Issue by rootxad** [maple3142/GDIndex#74]
Hey @maple3142 

Huge thanks for creating this code, in previous issue i told that virus detected files are returning with server error, than you updated the code with acknowledgeAbuse: true but now when i am trying to download other files which are not infected returning server error.

Demo: [link](https://root3.officialmohammadusman.workers.dev/UniProjects/Demofile) Not Working
Link with virus file: [link](http://root3.officialmohammadusman.workers.dev/UniProjects/Adobe_2020_Fix.rar) It takes a while to download as compared to regular file links. Working

Regards.

**Comment by maple3142** [comment]
It seems like there is no easy way to support both malicious files and normal files.
