### ISSUE TITLE
Is it possible to add decryption?

### ISSUE THREAD

**Issue by bnichs5** [maple3142/GDIndex#76]
Is it possible to add rclone decryption? And if yes, could it be applied to life mode?

**Comment by maple3142** [comment]
No

**Comment by bnichs5** [comment]
Ok thanks

**Comment by blackjack4494** [comment]
It is actually.
https://github.com/FWeinb/rclone-js
@maple3142

**Comment by maple3142** [comment]
I am not using rclone encryption, so I am not implementing it
