### ISSUE TITLE
#suggestion New Feature 

### ISSUE THREAD

**Issue by aryanvikash** [maple3142/GDIndex#8]
Is it possible To add Search feature inside it ?
because it hard to scroll and find everything.

**Comment by maple3142** [comment]
Ctrl+F ?

**Comment by aryanvikash** [comment]
Yeah it's working ... I was checking in phone

**Comment by maple3142** [comment]
Don't mobile browser have ability to do full text search in a website?
I checked Chrome and FireFox, and they do have this feature.
