### ISSUE TITLE
特定域和用户代理访问

### ISSUE THREAD

**Issue by rootxad** [maple3142/GDIndex#82]
有没有一种方法可以允许下载链接到特定域和用户代理：

Access-Control-Allow-Origin：example.com
Http-User-agent：等

通过这种方式，我们可以实现热链接保护.

**Comment by maple3142** [comment]
做了到，但是請自己研究

**Comment by rootxad** [comment]
Some source will be great.

**Comment by rootxad** [comment]
某些资料来源会很棒，我进行了很多研究，但无法实现我所寻求的目标。
