### ISSUE TITLE
脚本非常棒！不过不知道作者能否不久之后对以下问题进行优化？

### ISSUE THREAD

**Issue by hmglife** [maple3142/GDIndex#87]
1、希望能够实现上传文件夹和下载文件夹功能
2、希望能优化在线视频观看体验（如支持极其常用的mkv格式）
感谢作者制作的脚本！

**Comment by maple3142** [comment]
1. 請用官方的
2. 影片支援是瀏覽器決定的，關於 mkv 請搜尋之前別人發過的 issue
