### ISSUE TITLE
不能上传200m以上的文件

### ISSUE THREAD

**Issue by dengmotong** [maple3142/GDIndex#89]
部署在workers上不能上传200m以上的文件，不知道是workers的免费限制还是本身代码的限制

**Comment by dengmotong** [comment]
如果是workers的限制我认为可以使用google driver api里续传的功能实现上传大文件的功能，不知是否可以实现

**Comment by maple3142** [comment]
用了本來就是續傳的 api 了
還有上傳功能本來就只是額外的功能，還是請使用原版的來上傳

**Comment by PRStarDust** [comment]
我同样部署在worker上，发现使用http访问完全无法上传大文件，用https访问就可以上传，但是很容易失败
