### ISSUE TITLE
设置密码后访问仍不需验证

### ISSUE THREAD

**Issue by fanpest** [maple3142/GDIndex#99]
# Bug Description / 問題描述
不能验证密码

	user: '1',
	pass: '1',
账号密码已配置，可是仍然可以直接访问。
# Environment / 環境
workers
* Browser version / 瀏覽器版本:chrome
* OS version / 作業系統版本:win10

**Comment by maple3142** [comment]
自己重新設定看看
不會設定的話請用 builder
